paths:
  directory: /cosma8/data/dp004/flamingo/Runs/ #do not touch!
  soap_hbt_subpath: SOAP-HBT/halo_properties_00 #do not touch!

  simulation: L1000N0900/HYDRO_FIDUCIAL #only thouch this part!
  redshift_file: output_list.txt
  #we might wanna get the snapshotnumber outside of the config.yaml file to automate further!
  snapshot_number: [60,61,62,63,64,65,66,67] #for numbers below 10: fill in 06 or 07, not 6 and 7
  output_directory: results_angular_4 #full path if necessary

slicing:
  redshift_bin_width: 0.15 #delta_z of the complete bin, will mark the shell volume
  

random_catalog:
  seed: 12345 #random number, not very interesting to look at , We could later add None to recreate uncontrolled randoms.
  oversampling: 20 #the oversampling factor of the randoms

filters:
  central_filter: off
  stellar_mass_filter: on
  stellar_mass_cutoff: 0

  #survey: lrg #can also be bgs
  luminosity_filter: on

  survey: lrg #or lrg
  #bgs input, if survey=lrg we do not need any inputs
  m_r_cutoff: 21 #apparent band magnitude for the observer

  

plotting:

#--- mu ---
  mu_bins: 40
  mu_min: -1 #cosine 
  mu_max: 1  #cosine

#--- s ---
  s_bins: 200
  s_min: 0  #Mpc
  s_max: 300 #Mpc  #actually 300 Mpc!!!
  

statistics:
  n_patches: 100 #jackknife patches
