paths:
  base: /cosma/home/do012/dc-kort1/BAO
  simulation: L1000N3600/HYDRO_FIDUCIAL
  results_dir: results_illustris
  #mostly use the settings below, unless full paths are given
  redshift: 0.85
  cosmology: [illustris,w0waCDM] #correct one is always w0waCDM

plotting:
  correlation_2d: on
  variance_2d: on
  correlation_1d: on
  expected_bao_position: 150       # Mpc
  bao_window: 10                   # Mpc
  plot_bao: off
  mu_rebin: 1
  s_rebin: 2
